### ISSUE TITLE
[Run Error] monitors.xml missing

### ISSUE THREAD

**Issue by alex285** [GabMus/HydraPaper#1]
from Flatpak installation

```
flatpak run  org.gabmus.hydrapaper/x86_64/master
Traceback (most recent call last):
  File "/app/bin/hydrapaper", line 51, in <module>
    __main__.main()
  File "/app/lib/python3.5/site-packages/hydrapaper/__main__.py", line 368, in main
    application = Application()
  File "/app/lib/python3.5/site-packages/hydrapaper/__main__.py", line 78, in __init__
    self.monitors = MonitorParser.build_monitors_from_dict()
  File "/app/lib/python3.5/site-packages/hydrapaper/monitor_parser.py", line 26, in build_monitors_from_dict
    with open(path_to_monitors_xml) as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/alex/.config/monitors.xml'
```
Note i have a single monitor

**Comment by GabMus** [comment]
output of `cat /home/alex/.config/monitors.xml` pls. btw should work fine with one monitor

**Comment by GabMus** [comment]
wait you on wayland right? if so try xorg

**Comment by alex285** [comment]
@GabMus there is not a `~/.config/monitors.xml` file
im on Xorg. does it only work on Xorg?

**Comment by GabMus** [comment]
not sure, but you should have a monitors.xml file. maybe try changing the resolution in gnome settings and resetting it back to normal. I'm still not sure how and when monitors.xml is generated, I was sure enough that everyone had one

**Comment by GabMus** [comment]
also according to https://unix.stackexchange.com/questions/184941/gnome-prevents-high-resolution-vga-without-edid-info-over-vga monitors.xml is undocumented, but i'm still researching that

**Comment by alex285** [comment]
@GabMus sorry for the slow reply. i was trying to understand whats happening. i logged in my Ubuntu installation (original bug report was from Arch), and i dont have a `monitors.xml` file either there. from my understanding it doesnt even needed

i changed resolution as you asked me. 
first with `xrandr` but that didnt created an `monitors.xml` file. however when i changed resolution and back from Settings App, it created one

running HydraPaper it gave me a different error now
```flatpak run org.gabmus.hydrapaper/x86_64/master 
Traceback (most recent call last):
  File "/app/bin/hydrapaper", line 51, in <module>
    __main__.main()
  File "/app/lib/python3.5/site-packages/hydrapaper/__main__.py", line 368, in main
    application = Application()
  File "/app/lib/python3.5/site-packages/hydrapaper/__main__.py", line 78, in __init__
    self.monitors = MonitorParser.build_monitors_from_dict()
  File "/app/lib/python3.5/site-packages/hydrapaper/monitor_parser.py", line 28, in build_monitors_from_dict
    lm_list = doc['monitors']['configuration'][-1]['logicalmonitor']
KeyError: -1

```

my `~/.config/monitors.xml`

```
<monitors version="2">
  <configuration>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>HDMI-0</connector>
          <vendor>SAM</vendor>
          <product>S24E390</product>
          <serial>0x30343938</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
</monitors>
```

**Comment by GabMus** [comment]
Ok I should have fixed it, try this flatpak (had to zip it because .flatpak is not supported in gh issue comments)
[hydrapaper-11faa4d.zip](https://github.com/GabMus/HydraPaper/files/1658156/hydrapaper-11faa4d.zip)

**Comment by alex285** [comment]
@GabMus that worked! but now i see other issues, that i will open

**Comment by GabMus** [comment]
I'm closing this, but it's pretty clear how there's a problem here. if you didn't ever mess around with the display settings, you wouldn't have a monitors.xml file. I think I have to find a better way to get monitors layout. If you have any suggestion, please tell me.
