### ISSUE TITLE
[Feature Request] Add a way to enable/disable search paths, without removing location

### ISSUE THREAD

**Issue by alex285** [GabMus/HydraPaper#11]
currently on "Folders" popover we can either add or remove locations. can we please also have a checkbox/switch that enables/disables the locations, but without deleteting them?

![bug](https://user-images.githubusercontent.com/11244308/35634416-560536f6-06b4-11e8-8b7c-d05592f67bf9.png)

**Comment by GabMus** [comment]
sure 👌

**Comment by GabMus** [comment]
Added this feature, awaiting feedback. Here's a flatpak to test it.

[hydrapaper-aa16743.zip](https://github.com/GabMus/HydraPaper/files/1689827/hydrapaper-aa16743.zip)

**Comment by alex285** [comment]
@GabMus awesome! thank you! i close this! if i get some time i will try to make some mockups to help you get ideas, because the UI can get some improvements :)
