### ISSUE TITLE
Add to flathub?

### ISSUE THREAD

**Issue by nedrichards** [GabMus/HydraPaper#16]
Is there a milestone or other feature you want to add before adding the app to Flathub, or are you not interested? (no worries if not)

Other than requiring "--socket=system-bus", and not having OARS in the appdata there isn't too much that's missing from my perspective, and it's a cool app that more people should see!

**Comment by GabMus** [comment]
Want to push out some more features before submitting to flathub.

Also, the config file hydrapaper creates is hardcoded to be located in `$HOME/.config/hydrapaper.json`, I think I should move it to a flatpak specific directory, right? Please let me know more about this.

**Comment by GabMus** [comment]
Just made a submission
