### ISSUE TITLE
Configurations files are outside of Sandbox

### ISSUE THREAD

**Issue by alex285** [GabMus/HydraPaper#18]
i had some issues (i'll open them later) and i thought to remove cache etc to test on a clean run
so first i removed everything on
```
$HOME/.var/app/org.gabmus.hydrapaper
```
when i restarted the app, i noticed that it was keep loading the old configuration (folders). i found nothing on GSettings but i discovered this file

```
$HOME/.config/hydrapaper.json 
```
is it correct to have a configuration file there for a Flatpak?

**Comment by GabMus** [comment]
Not really, but I still have to realize the proper way of doing it

**Comment by GabMus** [comment]
Did some changes in b0a25fb, the config file and cache files should be in the right place now.

[hydrapaper-1.1.3-31-gb0a25fb.zip](https://github.com/GabMus/HydraPaper/files/1713250/hydrapaper-1.1.3-31-gb0a25fb.zip)

**Comment by GabMus** [comment]
Fixed favorites stack page not showing

[hydrapaper-1.1.3-33-g646b12a.zip](https://github.com/GabMus/HydraPaper/files/1713260/hydrapaper-1.1.3-33-g646b12a.zip)

**Comment by GabMus** [comment]
No feedback, it works apparently, closing

**Comment by alex285** [comment]
@GabMus  ah sorry, i missed that! yeah it works! thanks!

**Comment by GabMus** [comment]
No worries, just wanted to close this issue 😁

**Comment by GabMus** [comment]
No worries, just wanted to close this issue 😁
