### ISSUE TITLE
Lower rest windows when you set wallpapers

### ISSUE THREAD

**Issue by alex285** [GabMus/HydraPaper#19]
This is the same functionality with Chrome OS and Deepin Linux. When you open Hydra, the rest windows should be get lower so you can see the backgrounds you set. When you close it, the windows get raised again

this is kinda tricky to achieve it automatically, because someone might wants to keep Hydra open, even if he has set a wallpaper, so it might worth to have a button to manually "lower and raise" windows

**Comment by GabMus** [comment]
There *should* be a command I can issue to the wm/compositor/de? to lower all windows. Will have to investigate this further tho. Time for a trip to IRC!

**Comment by GabMus** [comment]
Added the button to do this, not sure about the icon, but the functionality should work fine.

[hydrapaper-1.1.3-35-g807bde6.zip](https://github.com/GabMus/HydraPaper/files/1713459/hydrapaper-1.1.3-35-g807bde6.zip)

**Comment by alex285** [comment]
@GabMus  on this flatpak i get
```
Traceback (most recent call last):
  File "/app/bin/hydrapaper", line 50, in <module>
    from hydrapaper import __main__
  File "/app/lib/python3.5/site-packages/hydrapaper/__main__.py", line 26, in <module>
    gi.require_version('Wnck', '3.0')
  File "/usr/lib/python3.5/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Wnck not available

```

**Comment by GabMus** [comment]
Will have to ask on IRC... Works fine outside of flatpak, but inside of it, apparently Wnck isn't part of either the GNOME Platform nor the SDK.

**Comment by GabMus** [comment]
Added libwnck as a dependency inside the manifest, here you go:

[hydrapaper-1.1.3-75-g5f665ba.zip](https://github.com/GabMus/HydraPaper/files/1714852/hydrapaper-1.1.3-75-g5f665ba.zip)

**Comment by alex285** [comment]
@GabMus nice one! A couple of issues
1. when windows are lowered, the icon should change to "Raise"
2. when you raise the windows there is an animation like you're switching workspace

if you cannot reproduce that, tell me to show you on a video

**Comment by GabMus** [comment]
1. Alright, doable. But I thought that putting a toggle there rather than a normal button would be enough.

2. That animation, I have no control over. I call the window manager and ask it to lower/raise a set of windows, that's all I do. File a bug to mutter if you don't like the animation :P

**Comment by alex285** [comment]
@GabMus im not sure if is the same, but for example Dash To Panel has an option to lower/raise the windows without this animation happening. it has a couple of different issues though

https://github.com/jderose9/dash-to-panel/blob/864ab8822b8f89828206b306527a071d7fda5ce1/appIcons.js#L1428

Budgie that is not using Shell (but mutter) also has such functionality

https://github.com/budgie-desktop/budgie-desktop/blob/master/src/applets/show-desktop/ShowDesktopApplet.vala

**Comment by GabMus** [comment]
I have to try a couple of things. I read on reddit something about GDK incorporating some Wnck functionality or something on that line. If this interface has show/hide methods, I can do that instead of minimizing/restoring. Will have to look into it tho.

**Comment by GabMus** [comment]
I actually found out that:

1. dash to panel does the same thing I do, so I'm not sure about what kind of wizardry it uses to inhibit the animation

2. budgie uses a function of wnck to *toggle show desktop*, and while that works and avoids the animation, you can't tell it *not* to hide hydrapaper, and that's a problem.

I think I will keep it the way it is until I find a better solution.

**Comment by GabMus** [comment]
Anyway, I think the core issue here is solved, closing this.
