### ISSUE TITLE
Arch Linux error: target not found: gtk3>=3.24

### ISSUE THREAD

**Issue by mattogrady87** [GabMus/HydraPaper#20]
The dependency on the AUR pkg is set to >=3.24 while ARCH current version is 3.22.28-1, therefore I cannot install. Do we truly need 3.24 or perhaps this was just an oversight?

Hope to get this working. Drives me crazy that this feature isn't built-in to Gnome, thank you for your work on it.

**Comment by GabMus** [comment]
fixed
