### ISSUE TITLE
Ability to use with CRON for a random wallpaper change

### ISSUE THREAD

**Issue by ThomasHineXYZ** [GabMus/HydraPaper#27]
I was wondering if it would be possible to add in a way to cycle through the favourites randomly for each monitor?

Probably using something like `CRON` to have it run on a fixed schedule. 

I haven't been able to find a _good_ way to do this aside from a custom script, but when using multiple monitors it can be an issue and add a level of difficulty to it...

**Comment by GabMus** [comment]
added option to use from cli as of #33
