### ISSUE TITLE
not working in GNOME-3.28.1

### ISSUE THREAD

**Issue by todork** [GabMus/HydraPaper#28]
$ flatpak --user install ~/hydrapaper-1.2.flatpak
Required runtime for org.gabmus.hydrapaper/x86_64/master (org.gnome.Platform/x86_64/3.26) is not installed, searching...
The required runtime org.gnome.Platform/x86_64/3.26 was not found in a configured remote.
error: The Application org.gabmus.hydrapaper/x86_64/master requires the runtime org.gnome.Platform/x86_64/3.26 which is not installed

The actual gnome version is:
$ gnome-shell --version
GNOME Shell 3.28.1

**Comment by GabMus** [comment]
Should be fixed, try with this flatpak: https://github.com/GabMus/HydraPaper/releases/download/1.2/hydrapaper-1.2.flatpak

**Comment by todork** [comment]
Still not working

**Comment by GabMus** [comment]
Did you install the newer flatpak I provided? What's the output when you try installing it?

Also, for better formatting, when you're copy-pasting terminal output, do it like this:

````
```
Terminal output here
```
````

**Comment by todork** [comment]
I downloaded twice
here is the output&
todork@todork-Precision-T1500:~/Свалени$ flatpak --user install hydrapaper-1.2.flatpak
Required runtime for org.gabmus.hydrapaper/x86_64/master (org.gnome.Platform/x86_64/3.26) is not installed, searching...
The required runtime org.gnome.Platform/x86_64/3.26 was not found in a configured remote.
error: The Application org.gabmus.hydrapaper/x86_64/master requires the runtime org.gnome.Platform/x86_64/3.26 which is not installed

I use ubnutu-18.04

**Comment by todork** [comment]
Sorry 
```
todork@todork-Precision-T1500:~/Свалени$ flatpak --user install hydrapaper-1.2.flatpak
Required runtime for org.gabmus.hydrapaper/x86_64/master (org.gnome.Platform/x86_64/3.26) is not installed, searching...
The required runtime org.gnome.Platform/x86_64/3.26 was not found in a configured remote.
error: The Application org.gabmus.hydrapaper/x86_64/master requires the runtime org.gnome.Platform/x86_64/3.26 which is not installed
```

**Comment by GabMus** [comment]
Try the following commands:

```
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak --user install flathub org.gabmus.hydrapaper
```

**Comment by todork** [comment]
Thanks, now it works perfectly!!!!

**Comment by GabMus** [comment]
Not sure what's wrong with the bundled package, but apparently the flathub version works. Happy to have helped!

**Comment by saamkhya** [comment]
How do you run the app after installing it using flathub?

**Comment by 4rtis4n** [comment]
Hi, I installed hydrapaper properly but I can't find the software while searching, using ubuntu 18.04

**Comment by jsosulski** [comment]
From terminal you can run it using

`flatpak run org.gabmus.hydrapaper`

**Comment by shiggitay** [comment]
@GabMus I just tried installing HydraPaper and I keep getting this error when I run it like this:

shiggitay@VocaloidHaven ~ $ hydrapaper
Traceback (most recent call last):
  File "/usr/local/bin/hydrapaper", line 62, in <module>
    gi.require_version('Handy', '1')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 133, in require_version
    (namespace, version))
ValueError: Namespace Handy not available for version 1

Why? I'm running GNOME 3.36.2 on Funtoo Linux but yeah.

**Comment by a0917bc** [comment]
> Try the following commands:
> 
> ```
> flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
> flatpak --user install flathub org.gabmus.hydrapaper
> ```

it works for me. Thanks for your sharing!!!
