### ISSUE TITLE
Could Hydra assist the creation of an XML wallpaper ?

### ISSUE THREAD

**Issue by maoschanz** [GabMus/HydraPaper#30]
"animated" wallpapers are supported by GNOME Shell (and others) but there is no way to manage them from system settings, and it looks like it's not supported by Hydra (at least i didn't see it)

Could Hydra:

- support XML files ?
- help creating one from a set of pictures ?

**Comment by GabMus** [comment]
It's not the scope of HydraPaper, maybe I could add such feature in the future, but I have no plans to.

**Comment by maoschanz** [comment]
actually since June i had time to code the app i wanted for this by myself ;)

**Comment by GabMus** [comment]
awesome, well done!
