### ISSUE TITLE
lockscreen background feature missing

### ISSUE THREAD

**Issue by h0n3ym4k** [GabMus/HydraPaper#38]
Hi guys,
   I have been using this flatpak on fedora 30. This app is great. Just wondering if "lock screen" background will be handled sooner or later >.^

**Comment by GabMus** [comment]
Hey thanks for opening this issue, I'll be working on it, shouldn't be too complicated. But for the future, don't open issues on github, as development moved to gitlab in this repo https://gitlab.com/gabmus/hydrapaper

**Comment by GabMus** [comment]
Feature added in version 1.9. In a couple of hours the update should be available via flatpak. Enjoy!
