### ISSUE TITLE
Image Adjustment to Scale

### ISSUE THREAD

**Issue by alex285** [GabMus/HydraPaper#4]
this video demonstrates the issue
https://youtu.be/HFCyn1aHuF8

**Comment by GabMus** [comment]
On single screen I just set the wallpaper rough from the fs, but didn't consider that problem. EZ fix, working on it now

**Comment by GabMus** [comment]
Should be fixed here

[hydrapaper-2f278be.zip](https://github.com/GabMus/HydraPaper/files/1659444/hydrapaper-2f278be.zip)

**Comment by GabMus** [comment]
Should be fixed, closing
