### ISSUE TITLE
HydraPaper can't change wallpapers on Pop OS 20.04

### ISSUE THREAD

**Issue by PoignardAzur** [GabMus/HydraPaper#40]
I'm currently using Pop OS 20.04, and I installed HydraPaper from Flathub to compensate from Pop Shell's inability to cycle through a list of wallpapers.

Unfortunately, HydraPaper currently doesn't seem to work on my machine.

I can open the application and use the GUI, but when I select any given wallpaper, Pop Shell's background is still the default wallpaper, even though HydraPaper's UI thinks the current wallpaper is the one I selected.

This is too bad, because HydraPaper's GUI is exactly what I want otherwise.

**Comment by GabMus** [comment]
This repo is abandoned, please reopen this issue here: https://gitlab.gnome.org/gabmus/hydrapaper

**Comment by PoignardAzur** [comment]
Oh. Sorry, I didn't notice.

You should probably migrate the remaining issues and disable the Issue tab then.

https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/disabling-issues
