### ISSUE TITLE
Single click for selection on flowbox please

### ISSUE THREAD

**Issue by alex285** [GabMus/HydraPaper#5]
i will describe 3 trivial UI issues here, instead opening 3 different bug reports

1. the selection should be on single click (see screenshot), rather double
2. when you first open the app, the current background is missing from the previewer (see screenshot)
3. can you please remove the title from the headerbar? it gets trimmed if we scale the app to a single column

![screenshot from 2018-01-24 05-53-59](https://user-images.githubusercontent.com/11244308/35313834-33f2273e-00cb-11e8-8c7d-97ac7b1da535.png)

**Comment by GabMus** [comment]
1. I really like double click tbh, it makes the selection of the wallpaper more intentional. But I will put an option for single click.

2. The image-missing icon is really intentional, but I see how that can be ugly. Any suggestion on what to put there instead if no wallpaper is selected?

3. I could remove the title, but this way the headerbar would be underwhelmingly empty. I don't think I want to do that really.

**Comment by GabMus** [comment]
1 solved: added setting to choose between single and double click mode, made single click default.

**Comment by alex285** [comment]
@GabMus 
1. i cant remember any such selection working with double click on GNOME (or anywhere else), so it is kinda confusing. if you [watch this](https://youtu.be/NvUjP_IjK68?t=1m5s), i'm getting confused even if i knew that it needs double click. in fact, when i first installed Hydra (nice name btw!), i thought it wasnt even working! and it will be even more weird on touch screens!

2. why it is intentional? it makes sense to see the current backgrounds set

3. about the title is just unnecessary, and i dont think it looks bad if the space is empty. on the above video, again you can see the issue when you scale the app to one column, which is kinda cool, if you want to see the wallpaper you select

btw one more tiny UI issue is the loading icon. the switch is so fast that is not needed, and it looks like a graphic glitch

**Comment by GabMus** [comment]
1. Single click is now default so i think that's fixed. Anyway you're right
about touch screens and general gnome consistency.

2. Alright, will have to save that to the config file tho lol

3. Will add a setting to hide the title maybe? Don't know, I don't like
empty stuff, and the headerbar is so big that not using it feels like
wasted space. Will think about this tho.

**Comment by alex285** [comment]
@GabMus  
> 3. Will add a setting to hide the title maybe? 

if you are going to add a setting just to display the appName (which is totally unnecessary info!), just leave it the way it is :)

**Comment by GabMus** [comment]
Fixed everything here. Making 1.1.2 release. Also try (re)moving your monitors.xml file and opening up hydrapaper, you'll se what happens!

**Comment by alex285** [comment]
@GabMus all good! im closing this! thank you!
if not a monitors.xml, it throws you that error message! if you could though find another way to get monitor's information, would be even better!

**Comment by GabMus** [comment]
> find another way to get monitor's information

Yeah, if you find any other way, ping me please
