### ISSUE TITLE
Unable to install flatpak

### ISSUE THREAD

**Issue by dabbill** [GabMus/HydraPaper#6]
flatpak install ~/Downloads/hydrapaper-1.1.2.flatpak
Updating: org.gnome.Platform/x86_64/3.26 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.26 from gnome
No updates.
Installing: org.gabmus.hydrapaper/x86_64/master from bundle hydrapaper-1.1.2.flatpak
error: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)

**Comment by GabMus** [comment]
try `flatpak --user install ~/Downloads/hydrapaper-1.1.2.flatpak`

**Comment by dabbill** [comment]
I am still getting the same error with that command

**Comment by cedarice** [comment]
Same error, me too.

**Comment by cedarice** [comment]
It need the dependence org.gnome.Platform//3.26, the following command will install it.
flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
flatpak remote-add --from gnome-apps https://sdk.gnome.org/gnome-apps.flatpakrepo
flatpak install gnome org.gnome.Platform//3.26

Then, download the hydrapaper-1.1.2.flatpak and install it with this command:
flatpak --user install ~/Downloads/hydrapaper-1.1.2.flatpak

**Comment by dabbill** [comment]
`flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo                                             
error: Remote gnome already exists
flatpak install gnome org.gnome.Platform//3.26                                                              
error: org.gnome.Platform/x86_64/3.26 already installed
flatpak --user install ~/Downloads/hydrapaper-1.1.2.flatpak                                                         
Installing: org.gabmus.hydrapaper/x86_64/master from bundle hydrapaper-1.1.2.flatpak
error: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)
`

**Comment by alex285** [comment]
@dabbill whats your `flatpak --version`
is it > 0.10?

**Comment by dabbill** [comment]
@alex285 
flatpak --version                                                                                                   
Flatpak 0.8.7

**Comment by dabbill** [comment]
@alex285 I added the flatpak repo and updated to FLatpak 0.10.2 and was able to install this flatpak. 

Thanks :)

**Comment by GabMus** [comment]
@alex285 thanks for giving support, it's appreciated ;D

I also added some more detailed instructions about flatpak in the readme file, to avoid future similar problems.

**Comment by alex285** [comment]
@GabMus the benefit to have multiple Linux installations! you know Ubuntu bugs :)
